/*
 * generated by Xtext 2.12.0
 */
package kurs.xtext.dataflow.validation

import kurs.xtext.dataflow.dataFlowDsl.KComponent
import org.eclipse.xtext.validation.Check
import kurs.xtext.dataflow.dataFlowDsl.DataFlowDslPackage

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DataFlowDslValidator extends AbstractDataFlowDslValidator {

	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkComponentStartsWithCapital(KComponent c) {
		if (!Character.isUpperCase(c.name.charAt(0))) {
			warning('Name should start with a capital',
				DataFlowDslPackage.Literals.KCOMPONENT__NAME,
				INVALID_NAME
			)
		}
	}

}
