/*
 * generated by Xtext 2.12.0
 */
package kurs.xtext.dataflow.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class DataFlowDslWebModule extends AbstractDataFlowDslWebModule {
}
